# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6174a51f5fd53751a0ef01d47da2fc3bc05facf6de6f758a8c0495169ef2945a31508bbaa6060708febab9ed14aeabe64ef6644cce31f11e111cd41de924c6d

test:
  secret_key_base: 5f6b92a5ca451b2a33008fe2e58ca50524b3892ed8c9629f29de88d6a5d830853e3a32f3617bf6ce273c06d16b77b5085abd8f98ce7182b4c11ee97aa7d15657

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
